FROM golang:latest

WORKDIR /go/src/euge
COPY . .
WORKDIR src/bookingservice
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bookingservice

FROM scratch

COPY --from=0 /go/src/euge/src/bookingservice/bookingservice /bookingservice
ENV LISTEN_URL=0.0.0.0:8181
EXPOSE 8181
CMD ["/bookingservice"]
